-- Databricks bronze tables (auto-translated from sql/bronze/002_create_bronze_tables.sql)
-- CREATE IF NOT EXISTS: safe to re-run; will NOT drop existing sample data.

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_customer (
    bronze_record_id BIGINT,
    customer_id BIGINT,
    customer_account_no STRING,
    business_name STRING,
    first_name STRING,
    last_name STRING,
    full_name STRING,
    email STRING,
    phone STRING,
    customer_status STRING,
    default_tax_rate_id BIGINT,
    home_store_id BIGINT,
    first_order_date DATE,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    source_row_version INT,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_customer_address (
    bronze_record_id BIGINT,
    address_id BIGINT,
    customer_id BIGINT,
    address_type STRING,
    street_address STRING,
    street_address2 STRING,
    city STRING,
    state_code STRING,
    zip_code STRING,
    is_primary_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_product (
    bronze_record_id BIGINT,
    product_id BIGINT,
    sku STRING,
    product_name STRING,
    description STRING,
    department_id BIGINT,
    category_id BIGINT,
    brand STRING,
    unit_cost_amount DECIMAL(12,2),
    markup_pct DECIMAL(8,4),
    standard_price_amount DECIMAL(12,2),
    is_local_made_flag BOOLEAN,
    is_active_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    source_row_version INT,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_product_category (
    bronze_record_id BIGINT,
    category_id BIGINT,
    department_id BIGINT,
    category_code STRING,
    category_name STRING,
    description STRING,
    is_active_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_department (
    bronze_record_id BIGINT,
    department_id BIGINT,
    department_code STRING,
    department_name STRING,
    description STRING,
    is_active_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_employee (
    bronze_record_id BIGINT,
    employee_id BIGINT,
    employee_code STRING,
    first_name STRING,
    last_name STRING,
    full_name STRING,
    email STRING,
    phone STRING,
    role STRING,
    store_id BIGINT,
    hire_date DATE,
    is_active_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    source_row_version INT,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_store (
    bronze_record_id BIGINT,
    store_id BIGINT,
    store_code STRING,
    store_name STRING,
    street_address STRING,
    city STRING,
    state_code STRING,
    zip_code STRING,
    phone STRING,
    region STRING,
    store_type STRING,
    open_date DATE,
    is_active_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    source_row_version INT,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_invoice (
    bronze_record_id BIGINT,
    invoice_id BIGINT,
    invoice_number STRING,
    customer_id BIGINT,
    store_id BIGINT,
    employee_id BIGINT,
    billing_address_id BIGINT,
    shipping_address_id BIGINT,
    po_number STRING,
    invoice_date DATE,
    invoice_due_date DATE,
    invoice_status STRING,
    tax_rate_id BIGINT,
    subtotal_amount DECIMAL(12,2),
    discount_amount DECIMAL(12,2),
    tax_amount DECIMAL(12,2),
    fee_amount DECIMAL(12,2),
    total_amount DECIMAL(12,2),
    paid_amount DECIMAL(12,2),
    balance_due_amount DECIMAL(12,2),
    notes STRING,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    source_row_version INT,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_invoice_line (
    bronze_record_id BIGINT,
    invoice_line_id BIGINT,
    invoice_id BIGINT,
    line_number SMALLINT,
    product_id BIGINT,
    variant_id BIGINT,
    line_description STRING,
    color STRING,
    order_qty INT,
    unit_price_amount DECIMAL(12,2),
    unit_cost_amount DECIMAL(12,2),
    discount_amount DECIMAL(12,2),
    line_total_amount DECIMAL(12,2),
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_payment (
    bronze_record_id BIGINT,
    payment_id BIGINT,
    invoice_id BIGINT,
    customer_id BIGINT,
    payment_method_id BIGINT,
    payment_type_id BIGINT,
    employee_id BIGINT,
    store_id BIGINT,
    parent_payment_id BIGINT,
    payment_sequence_num SMALLINT,
    payment_status STRING,
    payment_date DATE,
    gross_amount DECIMAL(12,2),
    tax_amount DECIMAL(12,2),
    fee_amount DECIMAL(12,2),
    net_amount DECIMAL(12,2),
    reference_no STRING,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    source_row_version INT,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_invoice_status_history (
    bronze_record_id BIGINT,
    status_history_id BIGINT,
    invoice_id BIGINT,
    old_status STRING,
    new_status STRING,
    changed_at_source_timestamp TIMESTAMP,
    changed_by BIGINT,
    note STRING,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_customer_status_history (
    bronze_record_id BIGINT,
    status_history_id BIGINT,
    customer_id BIGINT,
    old_status STRING,
    new_status STRING,
    changed_at_source_timestamp TIMESTAMP,
    changed_by BIGINT,
    reason STRING,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_refund (
    bronze_record_id BIGINT,
    refund_id BIGINT,
    payment_id BIGINT,
    invoice_id BIGINT,
    refund_amount DECIMAL(12,2),
    refund_date DATE,
    reason STRING,
    refunded_by BIGINT,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.oltp_invoice_adjustment (
    bronze_record_id BIGINT,
    adjustment_id BIGINT,
    invoice_id BIGINT,
    adjustment_type STRING,
    amount DECIMAL(12,2),
    reason STRING,
    adjusted_by BIGINT,
    adjustment_date DATE,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.ref_payment_method (
    bronze_record_id BIGINT,
    payment_method_id BIGINT,
    method_code STRING,
    method_name STRING,
    method_type STRING,
    is_card_flag BOOLEAN,
    is_active_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    source_row_version INT,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.ref_payment_type (
    bronze_record_id BIGINT,
    payment_type_id BIGINT,
    type_code STRING,
    type_name STRING,
    description STRING,
    affects_balance_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    is_deleted_source_flag BOOLEAN,
    deleted_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.ref_tax_rate (
    bronze_record_id BIGINT,
    tax_rate_id BIGINT,
    tax_code STRING,
    description STRING,
    rate_pct DECIMAL(6,4),
    effective_from DATE,
    effective_to DATE,
    is_active_flag BOOLEAN,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.ref_state (
    bronze_record_id BIGINT,
    state_code STRING,
    state_name STRING,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.ref_invoice_status (
    bronze_record_id BIGINT,
    status_code STRING,
    status_name STRING,
    is_terminal_flag BOOLEAN,
    sort_order SMALLINT,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.ref_payment_status (
    bronze_record_id BIGINT,
    status_code STRING,
    status_name STRING,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);

CREATE TABLE IF NOT EXISTS printtime_dw.bronze.econ_indicator (
    bronze_record_id BIGINT,
    series_id STRING,
    observation_date DATE,
    indicator_value DECIMAL(18,6),
    units STRING,
    created_at_source_timestamp TIMESTAMP,
    updated_at_source_timestamp TIMESTAMP,
    bronze_batch_id BIGINT,
    bronze_loaded_at_timestamp TIMESTAMP,
    bronze_extracted_at_timestamp TIMESTAMP,
    bronze_source_system STRING,
    bronze_source_table_name STRING,
    bronze_source_file_name STRING,
    bronze_source_row_number BIGINT,
    bronze_row_hash STRING,
    bronze_is_deleted_flag BOOLEAN,
    bronze_raw_payload_jsonb STRING
);
